version: "3.9"

services:
  php:
    build:
      context: docker/php/
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www/html
    container_name: php
    networks:
      - itproject
    ports:
      - 127.0.0.1:3500:80

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass

      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: pass
    container_name: mysql
    ports:
    - 127.0.0.1:3000:3306
    volumes:
    - ./mysql:/var/lib/mysql
    networks:
      - itproject

networks:
  itproject:
    external: true
    driver: bridge
